# Generated by Django 5.1.2 on 2025-05-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customauth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("pro", "Pro"),
                            ("enterprise", "Enterprise"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("features", models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name="user",
            old_name="is_premium",
            new_name="is_paid",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="premium_end_date",
            new_name="subscription_end",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="premium_start_date",
            new_name="trial_end",
        ),
        migrations.AddField(
            model_name="user",
            name="tier",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("pro", "Pro"),
                    ("enterprise", "Enterprise"),
                ],
                default="basic",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="trial_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="trial_used",
            field=models.BooleanField(default=False),
        ),
    ]
