services:

  web:
    build: .
    command: >
      sh -c "
      python wait_for_db.py &&
      uvicorn edgeAI.asgi:application --host 0.0.0.0 --port 8888 --reload
      "
    volumes:
      - .:/app
    expose:
      - 8888
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - edgeAI-network

  db:
    container_name: edgeAI_postgres
    image: postgres:${PG_VERSION:-16}
    volumes:
      - edgeAI-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - edgeAI-network


  nginx:
      container_name: edgeAI_nginx
      image: nginx:1.19
      ports:
        - "80:80"
      volumes:
        - ./nginx:/etc/nginx/conf.d
        - ./staticfiles:/app/staticfiles
      depends_on:
        - web
      networks:
        - edgeAI-network

  redis:
    container_name: edgeAI_redis
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - edgeAI-network

  celery:
    container_name: edgeAI_celery
    build: .
    command: ["celery", "-A", "edgeAI", "worker", "--loglevel=INFO"]
    volumes:
      - .:/app
    depends_on:
      - db
      - redis 
    env_file:
      - ./.env
    networks:
      - edgeAI-network

  celery-beat:
    build:
      context: .
    container_name: edgeAI_celery_beat
    command: ["celery", "-A", "edgeAI", "beat", "--loglevel=info"]
    depends_on:
      - redis
      - web
    env_file:
      - ./.env
    networks:
      - edgeAI-network

  flower:
    build:
      context: .
    container_name: edgeAI_celery_flower
    command: ["celery", "-A", "edgeAI", "flower", "--port=5555"]
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery
    networks:
      - edgeAI-network



volumes:
  edgeAI-postgres-data:

networks:
  edgeAI-network: